language: ruby

cache: bundler

rvm: 2.4.1

before_script:
  - gem install mdl
  - gem install awesome_bot

script:
  - mdl _posts/posts/ --style relaxed # lint markdown (docs -> github.com/markdownlint/markdownlint)
  - awesome_bot _posts/posts/* --allow-dupe --allow-redirect --white-list test.dev # lint links (docs -> github.com/dkhamsing/awesome_bot)

notifications:
  email: false
