title: Noah Bass
description: CS student at the University of Cincinnati. Swift. JavaScript. Node.js. Python. Mobile and web. www lover.

author:
    name: Noah Bass
    email: noah@noahbass.com

meta:
    ga: UA-41393710-1

url: http://noahbass.com

social:
    github: noahbass
    twitter: n_bass
    linkedin: noahthedeveloper
    email: hello@noahbass.com
    googleplus: NoahBass
    disqus: nbass


permalink: /posts/:title


plugins:
    - jekyll-sitemap


sass:
    sass_dir: _scss
    style: :compressed
