meta:
    title: Noah Bass
    description: Hi! My name is Noah and I'm a web designer and developer (I make websites) in Cincinnati. I love the www.
    ga: UA-41393710-1

url: http://noahbass.com

social:
    github: noahbass
    twitter: n_bass
    linkedin: noahthedeveloper
    email: hello@noahbass.com
    googleplus: NoahBass


permalink: /posts/:title


gems:
    - jekyll-sitemap


sass:
    sass_dir: _scss
    style: :compressed
